const data = {
    products:[
        {
            _id:'1',
            name:'Fiitjee notes',
            category:'physics',
            image:'/images/pics.png',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Fiitjee topper physics notes',
            category:'physics',
            image:'/images/pics2.jpg',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality chem product',
        },
        {
            _id:'3',
            name:'Fiitjee topper maths notes',
            category:'Maths',
            image:'/images/pics3.jpg',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Fiitjee topper Hindi notes',
            category:'Hindi',
            image:'/images/pics4.png',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Fiitjee topper English notes',
            category:'eng',
            image:'/images/pics5.png',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Fiitjee topper phy. edu. notes',
            category:'physical education',
            image:'/images/pics6.jpg',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'7',
            name:'Fiitjee topper english notes',
            category:'english',
            image:'/images/pics7.jpg',
            price: 500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'8',
            name:'Fiitjee topper notes',
            category:'Hindi',
            image:'/images/pics8.jpg',
            price:500,
            brand:'Notes',
            rating:5,
            numReviews:10,
            description: 'high quality product',
        },
    ]
}
export default data;
